---
  - name: Rebooting server to make changes effect
    shell: sleep 2 && /usr/sbin/shutdown -r now "Kernel update"
    async: 1
    poll: 0
    ignore_errors: true
    when: update_needed.stdout == "update"
    register: reboot_after_kernel_update

  - name: Waiting for {{ inventory_hostname }} to reconnect
    local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=60
    become: true
    when: reboot_after_kernel_update.changed
